---

- name: Add docker GPG public key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
#    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add Docker Repository
  become: yes
  copy:
    src: files/docker.list
    dest: /etc/apt/sources.list.d

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Configure docker to use systemd as a cgroups driver
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Start/enable docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
