---

# # Create User
- name: Create local user
  become: yes
  user:
    name: '{{ rpi_user }}'
    password: "{{ rpi_user_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: 
    - docker
    - sudo
    append: yes